### ISSUE TITLE
[Bug] Build verification is failing

### ISSUE THREAD

**Issue by mikealfare** [dbt-labs/dbt-bigquery#1269]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Build verification is failing when running `twine check dist/*`. This is happening across all supported versions.

### Expected Behavior

Build checks should pass.

### Steps To Reproduce

https://github.com/dbt-labs/dbt-bigquery/actions/runs/9668100685

### Relevant log output

```shell
Run twine check dist/*
  twine check dist/*
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.18/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.8.18/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.18/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.18/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.18/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.18/x64/lib
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/bin/twine", line 5, in <module>
    from twine.__main__ import main
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/twine/__init__.py", line 40, in <module>
    __uri__ = metadata["home-page"]
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/importlib_metadata/_adapters.py", line 54, in __getitem__
    raise KeyError(item)
KeyError: 'home-page'
```

### Environment

```markdown
- OS: ubuntu 22.04 LTS
- Python: 3.8.18
- dbt-core: N/A
- dbt-bigquery: 1.6 and later
```

**Comment by colin-rogers-dbt** [comment]
Resolving as upstream dependencies unborked themselves
